name: Playwright Tests

on:
  push:
    branches: [ main ]

  # ✅ Daily 9:30 PM IST
  schedule:
    - cron: '0 16 * * *'

  # ✅ Manual trigger option
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report